<?php $merchantman = Mage::registry('merchant');
?>

<?php $helper = Mage::helper('learning_merchant'); ?>
<?php echo 'Name -> '.$merchantman->getName();  ?>
<?php echo '<br>'; ?>
<?php echo 'Surname -> '.$merchantman->getSurname();  ?>
<?php echo '<br>'; ?>
<?php echo 'name -> '.$merchantman->getDescription();  ?>

<img src="<?php echo $helper->getImageUrl($merchantman->getImageUrl()); ?>" title="<?php echo $merchantman->getName(); ?>">
