<?php $slides = $this->getMerchantmans(); ?>
<?php $helper = Mage::helper('learning_merchant'); ?>
<ul class="bxslider">

    <?php foreach ($slides as $slide): ?>
        <li>
            <img src="<?php echo $helper->getImageUrl($slide->getImageUrl()); ?>" title="<?php echo $slide->getName(); ?>">
            <a href="#"><?php echo $slide->getName(); ?></a>
        </li>
    <?php endforeach; ?>

</ul>

