<?php $merchantmans = $this->getMerchantmans(); ?>
<?php $helper = Mage::helper('learning_merchant'); ?>
<ul class="bxslider">

    <?php foreach ($merchantmans as $merchant): ?>
        <li>
            <?php echo $merchant->getName(); ?>
        </li>
    <?php endforeach; ?>

</ul>

<?php foreach ($merchantmans as $merchant): ?>

    <li>
        <a href="<?php echo Mage::getUrl('merchant/index/detail', array('name' => $merchant->getSlug())); ?>">
            <?php echo $merchant->getName();  ?>
        </a>

    </li>
<?php endforeach; ?>
